### ISSUE TITLE
Change hosted location

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/meta#12]
Would it make more sense to host these docs at pycqa.org rather than meta.pycqa.org ?

**Comment by sigmavirus24** [comment]
I was thinking of that, but also was thinking we should probably try to make it a little nicer before making that the landing page. I'm also torn as to whether we want the documentation to be the landing page for pycqa.org.

**Comment by IanLee1521** [comment]
Makes sense, maybe the landing page should be a GitHub Pages page that potentially highlights the various member projects?

**Comment by sigmavirus24** [comment]
This is in both places now
