### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by tony** [PyCQA/meta#24]
There is a tendency to prefer permissive licenses in the Python community (ISC, MIT, BSD, Apache 2).

I notice some of the projects I'd like to use  in PyCQA have viral clauses. I believe these can introduce unforeseen complications for users and shift too much legal burden to them. I think it could be averted by sticking to a simpler license, where possible.

I contribute to GPL software (for compiled languages, at least). I like viral licenses, but only use them when there's a reason good enough to justify the potential complication they could introduce. Due to the nature of interpreted languages, the community tends to shy away from it in node/python/ruby and so on.

For those who aren't aware, it's perfectly safe to use a GPL/LGPL application as an application accessed through shell prompt or subprocess calls. However, Python also has a lot of integrations where things can be imported or triggered via a code. It's a scripting language.

There are issues of ambiguity viral licenses (including LGPL) introduce that even to this day aren't solved. We don't understand the repercussions of copy/pasting LGPL, of subclassing LGPL code, monkey-patching, etc. [Twisted actually switched away from LGPL in 2004](https://twistedmatrix.com/pipermail/twisted-python/2004-May/007944.html), and this question was brought up. 14 years later, we still don't know how Python really works with viral licenses.

The reason I hesitate with viral licenses in scripting-type languages is the uncertainty shifts to the person using the library/application. When I've seen questions come up, the conversation often concluded in them being advised to get a lawyer to help understand the ramifications of the legal language in viral licenses. That can be a burden that's averted completely by sticking to a simpler license.

Even if they are willing to seek counsel (and can afford it), it may not be helpful since their legal jurisdiction may not have tested it in court. They don't have a point of relation to how this widely distributed license is interpreted in their legal cases - making it harder for the lawyer to give the client seeking advice certainty. It's possible they may be advised to seek non-viral alternatives to avoid complication.

In worst-case scenarios, there are risks of accusations of a derivative license. Even if outside court, they can be a distraction.

The other reason why I think Python open source projects tend to use permissive licenses is compatibility. Permissively licensed code can be used by virally licensed projects (e.g. MIT code can be used in Libreoffice, LGPL), but it doesn't work the other way around: A permissively licensed project (open office) can't use code from a virally license project (Libreoffice) without becoming a derivative. That is, becoming virally licensed itself (if openoffice took in virally licensed code and distributed a copy of itself, that would be virally licensed, ergo the project would be virally licensed).

I think it'd be worth considering preferring simple licenses like ISC/MIT/BSD for the convenience and flexibility of the user. Not for the sake of taking opinions on licenses (virally licensed projects can still take in permissive code), but to avoid complication in the long term.

**Comment by sigmavirus24** [comment]
Hey @tony,

Thanks for bringing this up. I think the only potentially problematic interaction might be with flake8-import-order. Otherwise, it seems like pylint and its dependencies are the only other projects using copyleft licenses. Does that match your understanding?

Cheers,
Ian

**Comment by tony** [comment]
@sigmavirus24 flake8-import-order was the one I was looking at when I made this issue.

I noticed pylint was GPL, but didn't check to see that PyCQA has a repo for it until now.

To reiterate though, if the linters are used purely through subprocess/command line, I think it is OK in terms of copyleft licenses. However since it's Python, I imagine somewhere downstream someone could use these packages in library form.

**Comment by sigmavirus24** [comment]
While imaginable, I'm not sure how realistic it is for `flake8-import-order` to be used as a library. Astroid, however, is definitely someone might use as a library since it's a library built for `pylint`. I think the best we can do is discuss recommending permissive licenses for folks starting new projects but that's about it. If we're very concerned, the affected projects should be contacted directly to see if they're interested in going through the process of changing their license(s).

**Comment by tony** [comment]
In general, I (and I can only speak for myself) don't want to deal with the cognitive overhead of incorporating viral licenses when I'm running permissively licensed projects downstream. Worrying about the if's and stuff.

In my situation, it was tmuxp, and I was interested in incorporating flake8-import-order our travis CI builds. It's a fair statement that a derivative wouldn't be triggered, but down the line when I give custodianship of it to an organization, things are a lot simpler when all the cogs and gears are simple licenses. That's where I'm coming from.

And I think one difficulty is other people may experience similar feelings, but won't always chime in and make an issue about it (I have a reputation to be loud about it). I know at least for certain libraries, being permissive is a plus, esp. if it's commercial. On [libgit2](https://libgit2.github.com/)'s website, they use permissively licensing as a feature.

A final point, these issues aren't the case in compiled languages where the lines of something being a built binary, or a shared library, is clearly and easily distinguishable.

That's about all I have to say on the issue though. I think it's a good rule of thumb to keep licenses simple unless there's a good reason for it to be otherwise.

**Comment by tony** [comment]
@sigmavirus24 Is there any feedback on this?

Is there any room for MIT to be a standard license for the tools here?

At least to make future contributions licensed MIT? (Even if the current contributions are GPL?)

The more contributions that come in that are GPL, the more are locked in to that LICENSE. It means that if and when GPL's terms become a limitation downstream, there will holdouts that made smaller contributions trying to hold the project hostage under GPL.

Even LGPL, the more permissive of the GPL license, doesn't fit in context with scripting languages like Python. Python can be used in a modular way, it can be vendorized, code can potentially be copied. 

> While imaginable, I'm not sure how realistic it is for flake8-import-order to be used as a library.

I think it's a matter of maintaining a project to be compatible with future uses. GPL's derivative clauses open up a range of hypothetical problems with a grueling process to leave it. Permissive licenses like ISC/MIT/BSD don't incur this burden.

Can it at least be decided to make foregoing contributions to PyCQA projects be licensed as MIT/ISC/BSD (which infers GPL until prior contributors agree to re-license their contribution under a more permissive license).
