### ISSUE TITLE
verify github organization domain

### ISSUE THREAD

**Issue by graingert** [PyCQA/meta#39]
To get a pretty green verified badge someone (@PyCQA/owners-team) with ORG access needs to add a TXT record: https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain

[](url)
![image](https://user-images.githubusercontent.com/413772/91773590-fe4dcc80-ebde-11ea-99bb-ee30acd73db2.png)

**Comment by sigmavirus24** [comment]
meta.pycqa.org is already verified but GitHub requires us to verify we own python.org too which is unreasonable: 
![Screenshot from 2020-09-01 19-07-32](https://user-images.githubusercontent.com/240830/91917784-905ce000-ec86-11ea-9eaf-9a262c34ad99.png)

I would never expect anyone with DNS access for python.org to actually let us do that, so we're not getting that badge.

**Comment by ssbarnea** [comment]
Why is python.org required? Did anyone raised a ticket with PSF and was refused?

**Comment by IanLee1521** [comment]
It's required because this organization is a mailing list through the Python domain (`code-quality@python.org`). That's the part that is tripping it up.

**Comment by ssbarnea** [comment]
I asked on https://discuss.python.org/t/helping-pycqa-obtain-the-verified-github-badge/5118 -- lets see if we can get help with this.

**Comment by sigmavirus24** [comment]
I just don't think it's reasonable to ask the PSF in the first place. We're not associated beyond them graciously hosting the mailing list.

**Comment by ssbarnea** [comment]
Hmm... The reality is that use of `@python.org` email address as the mail organization support does make a strong association, regardless if in reality that is limited only to the mailing list. 

If no further association is desired, maybe it would make sense to switch to `code-quality@pycqa.org` and avoid confusions? (not a proposal).

**Comment by sigmavirus24** [comment]
> If no further association is desired, maybe it would make sense to switch to `code-quality@pycqa.org` and avoid confusions? (not a proposal).

If someone wants to set-up infrastructure to run mailman and start moderating the list there, I'll happily manage the DNS.

> The reality is that use of `@python.org` email address as the mail organization support does make a strong association, regardless if in reality that is limited only to the mailing list.

I can see that. I don't think `python.org` was the right domain for the mailing lists but I'm not sure that's a changeable thing at this point given the history of most of the lists. As it stands, though, there are many mailing lists `@python.org` that have no real affiliation with the PSF or python.org beyond being hosted on infrastructure that's specifically called out as being there for community members to use (which we are)

**Comment by sigmavirus24** [comment]
The reality we all have to accept here is that Microsoft/GitHub aren't catering their badges to open source organizations like ours. We really are abnormal to them. This is why they broke the ability for team maintainers to invite people to the team on behalf of the org. It's because organizations are really "corporations" as far as they're concerned. They won't fix that or introduce a permission for it, so it means that while I'm not the only person who can invite folks here, I'm the only one who does that work.

**Comment by ssbarnea** [comment]
I did not touch the admin side of mailman for a very long time but I suspect it has some support for domain aliases. We should find way to avoid setting up more infrastructure to maintain.

I also wonder if it is mandatory to expose the user mailing list there, my impression was the original design was to expose an admin contact there.

I am looking at https://github.com/ansible/ and I do not see any email advertised there, even if I know they have multiple mailing list. Maybe to solution is to just remove the email from there. Those in need will easily find it from other the readme/docs.

**Comment by sigmavirus24** [comment]
<img width="422" alt="Screen Shot 2020-09-02 at 10 34 18" src="https://user-images.githubusercontent.com/240830/92004476-e02fbb80-ed07-11ea-94c3-a26a529d29d5.png">

That email address is the best way to reach as many people in the organization. It's not called "Administratrive Email". It's unclear what that email should be used for
