### ISSUE TITLE
Need for .keep files?

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/meta#4]
Is there a need for the .keep files? e.g.

* build/.keep
* source/_static/.keep
* source/_templates/.keep

I believe that sphinx will create them if they are missing doesn't it?

**Comment by sigmavirus24** [comment]
It does not. The tests fail without those directories there. Until we have a logo, we won't need the `_templates` directory either.

**Comment by IanLee1521** [comment]
Strange... I just tried taking out the .keep files (and the then empty directories) and I didn't have any issues building either with tox or with sphinx directly (see #6) under bother Python 2.7.10 and 3.5.1...

**Comment by sigmavirus24** [comment]
The Travis job does fail without those directories. Were you using the exact flags that are in the tox.ini? Those print out warnings and turn them into hard errors. (It's a nice way of making sure the docs do not accrue any kruft.)

**Comment by IanLee1521** [comment]
I did add those flags (`-E` and `-W`).

The issue that was causing an issue was in the conf.py file. I submitted a different pull request #7, without removing `tox` as that came up as a concern in #6.
