### ISSUE TITLE
licence the logo, and host .svg somewhere

### ISSUE THREAD

**Issue by graingert** [PyCQA/meta#41]
In https://github.com/PyCQA/meta/issues/1#issuecomment-201368468 @glynnis created a great pycqa logo, however it's not clear what the re-use permissions are.

I'm currently using it here to indicate a redirect: https://github.com/python-modernize because the "retro" default github gravatar makes a project look dead.

I believe this is fair use because I'm using the logo "to aid and promote public identification and recognition" of the pycqa. But I'm happy to remove it regardless.

**Comment by graingert** [comment]
Pinging @sigmavirus24 because I think the licence of this logo is important

**Comment by sigmavirus24** [comment]
Yeah, I don't think I got anything in writing from Glynnis so I think she still owns the copyright technically

**Comment by sigmavirus24** [comment]
I can't find an email either with the .AI files

**Comment by sigmavirus24** [comment]
I also don't particularly want to bug Glynnis about this, we could create a new logo for the org that we have properly licensed/etc.

**Comment by glynnis** [comment]
I'm happy for it to be used in the context on Github as linked above. I don't have a deep familiarity with various licenses, but the only usage I'd have a problem with is if someone is using the logo for financial gain e.g. slapping it on t-shirts and selling them. I'd be open to chatting about that, but generally for logos I've made as passion projects/for free, I don't like to see people using them to turn a profit.

I hope that's enough guidance to answer questions here! I _might_ still have vector files somewhere but will need to go spelunking through some old hard drives to find them if they exist. I'll try and do that this weekend, but no promises! If having the vectors is important and you haven't heard back from me in a week or two, feel free to @ me here again to remind me.

Thanks @sigmavirus24 for your consideration <3 If it's better for whatever usage/licensing y'all have in mind to just do a new logo that better fits your use cases, proceed!

**Comment by graingert** [comment]
@glynnis in terms of a licence as copyright holder you can always ease terms but cannot re-restrict terms so I'd recommend you start with the most restrictive license (that allows derivatives)

Attribution-NonCommercial-
ShareAlike 4.0 International (CC BY-
NC-SA 4.0)

And then chip away at it as you feels comfortable and needs arise

**Comment by glynnis** [comment]
Just updated this issue with link to vector files: https://github.com/simple-icons/simple-icons/issues/3623#issuecomment-765710974

**Comment by glynnis** [comment]
And FWIW, the CC BY-NC-ND license sounds good to me. Derivatives used in social media posts, sharing, informational materials, printed materials for informational purposes (business cards, fliers, etc.) are fine. 

My main concern with the license is to limit sale of merchandise with the logo so it can't be placed on e.g. t-shirt that someone profits from selling when I created the original work without that intent. Should someone want to sell merchandise or otherwise profit off of the sale of something where the logo is used, I'd ask them to contact me at glynnis.ritchie@gmail.com.

**Comment by graingert** [comment]
@glynnis thanks for finding and licencing these files for us! I've made a PR with those files, and licence, so we don't lose them
