### ISSUE TITLE
opt into https://github.com/github/renaming

### ISSUE THREAD

**Issue by graingert** [PyCQA/meta#42]
this will require a @PyCQA/owners-team member to

- [ ] go here https://github.com/organizations/pycqa/settings/repository-defaults#default_branch_name and fill in `main`

Secondly, require new repositories opt into the new name: https://github.com/PyCQA/meta/issues/38

see also https://github.com/github/renaming

**Comment by graingert** [comment]
For existing repos I think it would be best to wait for "the seamless-move" feature to land later this year, before considering enforcement.

https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

**Comment by IanLee1521** [comment]
I'm 👍 for this, looks like the link is https://github.com/organizations/pycqa/settings/repository-defaults#default_branch_name though

**Comment by graingert** [comment]
> I'm 👍 for this, looks like the link is https://github.com/organizations/pycqa/settings/repository-defaults#default_branch_name though

Thanks I fixed the link now

**Comment by sigmavirus24** [comment]
![image](https://user-images.githubusercontent.com/240830/92328425-542ed400-f026-11ea-8372-e7b78a8a2c71.png)

Done
