### ISSUE TITLE
https://pylint.pycqa.org/ keeps redirecting to non-HTTPS link

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/meta#43]
I'm not sure who looks after the hosting of this domain, but I was hoping that someone here might know. Here's the original issue posted on pylint's issue tracker (https://github.com/PyCQA/pylint/issues/3802):

> I am unsure if this repo is the best place to raise this issue, but I have noticed that https://pylint.pycqa.org/ keeps redirecting http://pylint.pycqa.org/en/latest/ which is a HTTP link instead of the HTTPS link https://pylint.pycqa.org/en/latest/. I am unsure what other languages the pylint documentation maintains, but I have been experiencing the problem for English.

**Comment by graingert** [comment]
@AWhetter I think this can be done from your end, but a meta level issue would be to enable hsts-preload on the domain

**Comment by sigmavirus24** [comment]
@AWhetter I believe there's something to do with ReadTheDocs. There are other issues here related to this. If there's something I need to do with the DNS, let me know.

**Comment by sigmavirus24** [comment]
I fixed up the DNS based on https://github.com/PyCQA/meta/issues/8 ... turns out I hadn't actually managed to get all the domains when I last updated this. Try flipping the switch in ReadTheDocs again @AWhetter ... This should also be fixed for pydocstyle and baron, which were the other outliers

**Comment by sigmavirus24** [comment]
I'm going to close this though and investigate if there's a way to manage DNS via octodns + Gandi

**Comment by graingert** [comment]
@sigmavirus24 pycqa is run with cloudflare right? You could enable hsts preload

**Comment by sigmavirus24** [comment]
> pycqa is run with cloudflare right?

I've no cloudflare account so if anything is using it with the PyCQA.org domain that'd be surprising

**Comment by graingert** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=pylint.pycqa.org&s=104.17.33.82&latest

Claims to be "Cloudflare Inc RSA CA-2"

**Comment by sigmavirus24** [comment]
I believe RTD used cloudflare
