### ISSUE TITLE
Is prospector abandoned?

### ISSUE THREAD

**Issue by Deimos** [PyCQA/meta#48]
Is the prospector tool (https://github.com/PyCQA/prospector) abandoned?

It hasn't had any updates in 9 months and is currently broken if you install updated versions of pylint/astroid (which can be necessary for reasons like fixing false positives related to type annotations).

Should I (and all the other users) be migrating away from it?

**Comment by sigmavirus24** [comment]
This has been discussed on the mailing list which has public archives. This repository is not the appropriate place for that discussion.
