### ISSUE TITLE
Please update Getting In Touch file to emphasize mailing list

### ISSUE THREAD

**Issue by Deimos** [PyCQA/meta#49]
Sorry about [my previous issue](https://github.com/PyCQA/meta/issues/48) (and even more so about opening another one, but I can't reply there since it was locked).

Please update this file if issues on this repo are not the way you would prefer to be contacted: https://github.com/PyCQA/meta/blob/master/source/getting-in-touch.rst

I created the issue because that file says it's the way to start a discussion with the PyCQA team. The way it's written right now makes it sound like opening an issue is the primary contact method, and the mailing list is mentioned as more of a side note.

*(and I've found the discussion about prospector on the list now, thank you)*

**Comment by sigmavirus24** [comment]
I've restructured https://meta.pycqa.org/getting-in-touch.html to try to push people to the mailing list first. Thakns for the suggestion!
