### ISSUE TITLE
flake8-colors is looking for a new family

### ISSUE THREAD

**Issue by and3rson** [PyCQA/meta#50]
Hi, I'm an author of the little `flake8-colors` lib.

At some point it was being used in `flake8` itself, however due to lack of time I was not able to maintain it properly and its quality has degraded.

Since this library is still being used by some people, I'm looking for someone who can adopt this library. I could transfer it under `PyCQA` organization if you guys would be interested in maintaining it.

Thanks for your attention!

**Comment by sigmavirus24** [comment]
@asottile thoughts on just incorporating this directly into flake8?

**Comment by asottile** [comment]
yeah I think I'll just implement the functionality in flake8 itself

**Comment by DanielNoord** [comment]
@sigmavirus24 Now that https://github.com/PyCQA/flake8/issues/1379 is closed I think this could be closed as well 😄
