### ISSUE TITLE
Dead link to code-of-conduct

### ISSUE THREAD

**Issue by ericwb** [PyCQA/meta#51]
The README contains a dead link to the code-of-conduct.  

In https://github.com/PyCQA/meta/blame/main/README.rst#L31
you'll find this link:
https://meta.pycqa.org/en/latest/code-of-conduct.html

I believe it should be pointing to:
https://meta.pycqa.org/code-of-conduct.html

**Comment by IanLee1521** [comment]
Got it, thanks @ericwb !
