### ISSUE TITLE
discord invitation link is invalid

### ISSUE THREAD

**Issue by finswimmer** [PyCQA/meta#53]
Hello,

looks like the discord link in https://github.com/PyCQA/meta/blob/main/source/getting-in-touch.rst is not valid anymore. Is the server still in use and only the link is expired, or doesn't it exist anymore?

fin swimmer

**Comment by sigmavirus24** [comment]
Thanks for pointing that out. I've updated it with a link that doesn't expire: https://discord.gg/D3RTpU9zEj

See you there soon!
