### ISSUE TITLE
pylint-pytest plugin's repo has been made private

### ISSUE THREAD

**Issue by nsp** [PyCQA/meta#56]
If you go to the [pylint-pytest](https://github.com/reverbc/pylint-pytest) repo page now, it returns a 404. In my own github history, I see that my activity on the repo (opening and commenting on issues) is reported as a "contribution in private repositories"

I believe that this plugin, despite its flaws and lack of recent releases, is critical for users of both pylint and pytest. It's even recommended in the pylint documentation ([example](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/redefined-outer-name.html)

Possible solutions I would support (in terms of participation and my own developer hours)
1. The plugin be incorporated into pylint itself
2. A fork of the repo be hosted by the PyCQA github org
3. A fork of the repo be hosted as a personal repo of mine but linked by the PyCQA docs

**Comment by Pierre-Sassoulas** [comment]
We pylint contributors and triagers might be responsible for this as we deferred all pylint's pytest related bugs on this repository which could have added too much pressure on the unwiling maintainer. I would favor to create a repository for each pylint plugin in an organisation. The organisation for that is to be determined as no current pylint maintainers is an admin in PyCQA. and I don't want to create more pylint related repo as long as #54 is not resolved.

**Comment by nsp** [comment]
OK, sounds good. In the meantime, I have a fork of the repo in my personal space: https://github.com/nsp/pylint-pytest

**Comment by DanielNoord** [comment]
Just to let you know, I have been working on an alternative over on https://github.com/DanielNoord/pylint-pytest-plugin. It takes a different approach than the other plugin so it's not a direct fork, but I intend to maintain it and any suggestions for fixes/feature requests are welcome.

**Comment by nsp** [comment]
@DanielNoord - Thanks! I'll check it out, and let you what false positives it misses, if any.

**Comment by Pierre-Sassoulas** [comment]
@reverbc sorry to ping you, and sorry for re-routing issues to your project without discussing it with you beforehand. What's your opinion about the future of pylint-pytest ?

**Comment by reverbc** [comment]
If anyone wants to contribute to the project as the main maintainer I'll do whatever that person wants, whether to reopen the project, move it to a different org, merge the capabilities into @DanielNoord's plugin or else. I have no preference or opinion for the future of the plugin.

**Comment by The-Compiler** [comment]
@reverbc Hey! :wave: One thing I'd suggest, if you don't mind, is to reinstate the project and [archive it](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) instead of deleting it or making it private. Archived projects are still visible but read-only, so no new issues/PRs can be opened anymore, and GitHub shows a banner clarifying that this is an archived project.

That way, people will still have a read-only copy of the code available (without needing to hunt down forks), rather than being greeted by a 404 when they e.g. follow old links to your repository. It would make it clearer to people that you're not interesting in maintaining the project further (which is perfectly fine of course!), rather than them being left wondering what happened.

Perhaps you could even do a quick edit to the README, e.g. pointing to @DanielNoord's new plugin as an alternative, before archiving it?

Thanks for all your work on it!

**Comment by Pierre-Sassoulas** [comment]
I've been able to fork pylint-pytest into PyCQA : https://github.com/PyCQA/pylint-pytest. Not sure if it's the right approach, or if it's possible to merge it with @DanielNoord plugins but I think it would be better if efforts were combined in a single plugin. Waiting for opinions before upgrading pylint's doc.

**Comment by mbyrnepr2** [comment]
In principle this sounds good to me, retaining the existing code. Would a transfer be better than forking, in order to retain existing pull requests, watchers etc? https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by ssbarnea** [comment]
Approach that I used in the past was to archive project and 3-6 months later to make it private, which is better than just removal.

**Comment by stdedos** [comment]
Would "you people" consider re-connecting the broken fork chain?

i.e. https://github.com/reverbc/pylint-pytest and https://github.com/gcapu/pylint-pytest

I'd like to pull "cleanly" https://github.com/reverbc/pylint-pytest/pull/22 on the https://github.com/PyCQA/pylint-pytest

**Comment by nsp** [comment]
Thank you for moving the project to https://github.com/PyCQA/pylint-pytest . 

I retargeted my MR to that repo, as https://github.com/PyCQA/pylint-pytest/pull/3, and it has had no response for a month. Now that the project is moved, how do we follow through and make this an active project again?

**Comment by anis-campos** [comment]
Nice, we could not use the plugin because of this issue https://github.com/PyCQA/pylint-pytest/pull/4, this might finally come to pass.

I still wondering though, even if the the project is moved here, will it be able to push new version to pypi under the same name ?

**Comment by stdedos** [comment]
@reverbc would you mind passing pypi rights to me?

**Comment by stdedos** [comment]
Good news! I am, as of today, officially a maintainer of pylint-pytest in pypi! 🎉 

And also, pylint-pytest has a new home https://github.com/pylint-dev/pylint-pytest  🎉  🎉  🎉 

For people that want to contribute, please target your fixes there.
If you'd like to re-join your forks, please ask Github to help you with that (I don't assume @Pierre-Sassoulas would have a problem with that - or idk I can approve that myself).
First order of business, however, would be to merge https://github.com/pylint-dev/pylint-pytest/pull/1/files 😅 

My open-source time is limited - but I promise to at least get "currently working fixes" in a merge queue within this month.
Additionally, also support pylint v3 (https://github.com/pylint-dev/pylint/issues/9144).

**Comment by webknjaz** [comment]
It seems like this issue can be closed now?
