### ISSUE TITLE
pylint-plugin-utils Ownership rights restoration

### ISSUE THREAD

**Issue by carlio** [PyCQA/meta#58]
Hello, it seems that I no longer have the ability to change settings on https://github.com/PyCQA/pylint-plugin-utils which suggests I am no longer an admin or owner.

I appreciate there has been significant inactivity there, but now I am going through and trying to tidy up and fix a lot of my projects so it would be good to have that permission back.

**Comment by DanielNoord** [comment]
You and the rest of https://github.com/orgs/PyCQA/teams/pylint-extras-dev are now maintainers. Is that sufficient?

**Comment by carlio** [comment]
Not really, I would like full ownership back since it was removed without notification or asking. Unless I'm mistaken, I would not be able to add new maintainers, for example.

**Comment by DanielNoord** [comment]
Ah my bad. I didn't know about the prior history and your moving of some of your projects.

I'll correct this somewhere in the next 24h when I'm back behind my laptop!

**Comment by sigmavirus24** [comment]
You were never an organization owner @carlio and as far as GitHub, the organization is the owner. There's no way to make you a repo owner without giving you permissions to nuke pylint or other projects

**Comment by DanielNoord** [comment]
> You were never an organization owner @carlio and as far as GitHub, the organization is the owner. There's no way to make you a repo owner without giving you permissions to nuke pylint or other projects

We can give the https://github.com/orgs/PyCQA/teams/pylint-extras-dev team `admin` rights to the repository right?

**Comment by sigmavirus24** [comment]
I've used different teams for different permission levels so people can grant finer grained permissions based on teams. I tend not to give admin to a dev team. I'm on mobile so I can't look at the current team structure for these but admin only fixes the settings piece. Admins can add people to the repo directly and I do go through and invite people based on the reports from GitHub of external contributors added to a repo periodically but it's not what Carl is asking for

As of about a year or so ago, GitHub changed the behavior such that only owners can invite new members. This was of course the right choice for companies and their enterprise users but harmed us as an org of diverse people.

Best we could do is set up something like jazzband has but that would allow anyone to join which we don't really want either.

**Comment by DanielNoord** [comment]
![image](https://github.com/PyCQA/meta/assets/13665637/8eec1444-508c-4dbb-a2e7-bf57f1154542)

We could at least add this right? Or does that give organization wide admin access (it doens't seem like it). Carl can then ping me if he wants to add somebody to the organization while they themselves would then be able to add them as maintainer to the respective repository.

**Comment by sigmavirus24** [comment]
![Screenshot-2023-05-30T08:58:15](https://github.com/PyCQA/meta/assets/240830/6d03e9e0-5332-423f-b9e2-60a301133dd5)

This is the team that should have admin. It has @carlio in it. I don't believe anyone else is in it and @carlio can invite whomever they want to it.

@carlio if you add people directly to the repository eiter @DanielNoord or I can see that and invite them to the org to the dev team. After that, if you'd like, you can add them to the admin team.

**Comment by carlio** [comment]
Ok I understand now, sorry for the confusing terminology. I merely meant repository ownership, not organisation ownership!

Anyway everything seems to have been resolved now, thank you :-)
