### ISSUE TITLE
PyCQA and GitHub Marketplace Developer Agreement

### ISSUE THREAD

**Issue by ericwb** [PyCQA/meta#61]
We would like to create an official GitHub Action for Bandit. We have a repo and action all defined and working here https://github.com/PyCQA/bandit-action. However, we can't publish the action to the marketplace to made it readily available to everyone without the organization accepting the GitHub Marketplace Developer Agreement.

This is the message from GitHub when trying to publish to marketplace:
```
PyCQA must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.
```

Can the PyCQA org admins please accept the GitHub Marketplace Developer Agreement?

Thanks!

- https://docs.github.com/en/site-policy/github-terms/github-marketplace-developer-agreement
- https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#publishing-an-action

**Comment by DanielNoord** [comment]
Thanks, taken care of. I didn't find anything suspicious in the Agreement and saw many other big name Python tools had also accepted it. You should be able to publish now!

**Comment by ericwb** [comment]
Thank you!
