### ISSUE TITLE
Set up TLS for pycqa.org and subdomains

### ISSUE THREAD

**Issue by sigmavirus24** [PyCQA/meta#8]
I think we can combine a simple server, Let's Encrypt, and https://docs.readthedocs.org/en/latest/alternate_domains.html#cname-ssl to get TLS for all of our subdomains as we deem them necessary.

**Comment by asottile** [comment]
An easier route (that's also free) that I've set up for my domains is using cloudflare's free plan.  Works great for https://pre-commit.com (github pages)

**Comment by jriddy** [comment]
This is affecting incoming links from google. Now that https is being served but the cert doesn't match the domain (it's for *.readthedocs.org), browser (correctly) complain about the cert-domain mismatch.

I made an issue [here](https://gitlab.com/pycqa/flake8/issues/530)

**Comment by ericvw** [comment]
I'm constantly running into this when being redirected from Google searches with `https://` being preferred.

What I receive is: `NET::ERR_CERT_COMMON_NAME_INVALID`

When trying to access https://flake8.pycqa.org/en/latest/...

> This server could not prove that it is __flake8.pycqa.org__; its security certificate is from __*.readthedocs.io__. This may be caused by a misconfiguration or an attacker intercepting your connection.

The workaround I have to do every time is change `https://` to `http://` to proceed forward.

**Comment by asottile** [comment]
@sigmavirus24 I'd be happy to set up https through cloudflare given the proper credentials -- it was quick,, easy, and free for the 5 or 6 domains I'm currently maintaining right now

**Comment by webknjaz** [comment]
@asottile I'm pretty sure if you go to RTD https://readthedocs.org/dashboard/flake8/domains/ and tick "Always use HTTPS for this domain" checkbox, it'll make RTD set a proper certificate. They support HTTPS out of the box for about a year I think.

**Comment by asottile** [comment]
the option was already checked -- I've toggled it we'll see if that does anything 🤷‍♂

**Comment by webknjaz** [comment]
"Have you tried turning it off and on again?"

**Comment by asottile** [comment]
It's still in the `SSL certificate status: pending_validation` state, maybe once that clears this'll be fixed?

**Comment by webknjaz** [comment]
It should. Otherwise, report it @ https://github.com/readthedocs/readthedocs.org/issues/new.

**Comment by asottile** [comment]
dang, looks like the `CNAME` configuration for the subdomain is incorrect so that's why it is stuck in `pending_validation`:

```console
$ dig flake8.pycqa.org CNAME +short
flake8.readthedocs.io.
```

apparently it has to be _just_ `readthedocs.io` -- I don't have access to fix this so I think @sigmavirus24 needs to handle that part

**Comment by webknjaz** [comment]
Oh, right. Forgot about that. Check cheroot.cherrypy.org with `dig`, it's configured properly.

**Comment by webknjaz** [comment]
Make sure you use `readthedocs.io` and not `readthedocs.org`. They autoprovision TLS certs only for one of these. And with the other you should use a CloudFlare proxy.

**Comment by ssbarnea** [comment]
I think that after 3 years the ticket title and description became totally misleading. Now we either need to review the domain, or to looks for alternatives like going back to RTD or maybe asking PSF to delegate us a subdomain maybe?

**Comment by sigmavirus24** [comment]
I'm pretty sure this works now.

**Comment by sigmavirus24** [comment]
Also I set up pycqa.org to point to meta.pycqa.org

**Comment by webknjaz** [comment]
Confirmed. Works for me.
